### ISSUE TITLE
Choose default port

### ISSUE THREAD

**Issue by dorianim** [jittering/traefik-kop#1]
Hey there,

Thank you so much for creating this! It is exactly what I've been looking for :D

I just have one small feature request: When there is only one exposed port on a container, could you automatically assign that port as the bind port?

Regards,
Dorian

**Comment by chetan** [comment]
I thought about this as well but since I'm mostly leveraging existing traefik code, this isn't something they normally pull from the docker API.

If I have time, I might look into the effort to pull this extra bit of info and tie it in.

**Comment by dorianim** [comment]
Thak yout for implementing this! I'll test it tomorrow :slightly_smiling_face:
