### ISSUE TITLE
Handle containers with static IPs

### ISSUE THREAD

**Issue by revnull-src** [jittering/traefik-kop#13]
I Just came across your very handy service. I have several containers that use a macvlan type network and statically defined IPs on the same vlan as the docker host(s). Example, a docker host has an IP of 192.168.1.10, the pihole container on that host is using 192.168.1.50:80|53. In this case, your service is reporting the pihole admin web service is at http://192.168.1.10:80 (docker host) instead of the container static IP of http://192.168.1.50:80. It seems that there my be additional information that needs to be parsed to account for containers that use static, bridge, and external DHCP container networks.

Thanks!

**Comment by revnull-src** [comment]
I just this PR that may resolve my issue. https://github.com/jittering/traefik-kop/pull/8 👍🏾

**Comment by chetan** [comment]
@revnull-src did you try out that change? The PR looks good but was waiting for some changes to be made before merging. I can clean it up and get it merged after some testing.

**Comment by chetan** [comment]
Pushed new docker images tagged `:latest` and `:0.11`
