### ISSUE TITLE
Default Rule

### ISSUE THREAD

**Issue by Svenum** [jittering/traefik-kop#18]
Is it possible to add a defaultRule?
Like the docker provider:
``` yml
defaultRule: "Host(`srv-{{ index .Labels \"com.docker.compose.service\"}}.example.com`)"
```

Would be very helpfull.

**Comment by chetan** [comment]
@Svenum I don't understand what you mean here. Where would this rule be added and what are you trying to achieve? I guess you are looking for the equivalent of the traefik provider-level config [referenced here](https://doc.traefik.io/traefik/providers/docker/#defaultrule)?

**Comment by Svenum** [comment]
Yes, I am looking for something like the defaultRule from the Docker provider in Traefik.
![image](https://user-images.githubusercontent.com/43136984/193827896-b6702c22-c9ed-49ca-b304-8755278a4e56.png)
I want, that I don't have to add to every container the label with the rule.
`traefik.http.routers.ngnix.rule`

**Comment by chetan** [comment]
Hi @Svenum,

I pushed a new pre-release build which solves this as well as #17. You can try it out via this tag: `ghcr.io/jittering/traefik-kop:0.12.2-next-amd64`. You can see the arm tags on the [packages](https://github.com/jittering/traefik-kop/pkgs/container/traefik-kop) page if you need those instead. 

See the new [`docker-config`](https://github.com/jittering/traefik-kop/tree/feature/docker-provider-config#traefik-docker-provider-config) and [`label`](https://github.com/jittering/traefik-kop/tree/feature/docker-provider-config#traefik-kop-service-labels) options in the branch readme file.

Please report back and let me know if it works for you so I can go ahead and cut a new release.

**Comment by Svenum** [comment]
Nevermind it works fine, I only have to restart traefik and redis.

**Comment by chetan** [comment]
@Svenum thanks for providing a test case. I'll give it a go when I've got some time and see if I can reproduce. 

That said, it looks the error is something to do with the default rule config. Can you try running kop with `DEBUG: "1"` env var and check the output on startup? I can also add a dump of the docker provider config as an extra bit for debugging.

**Comment by chetan** [comment]
You can also try the very latest build here, just to ensure you got the write image: `ghcr.io/jittering/traefik-kop:0.12.2-next-22aaa3b-amd64`

**Comment by Svenum** [comment]
The Default rule and the bind_ip Label Work fine but i geht this Error anyway. I'll try the latest build tomorrow.

**Comment by chetan** [comment]
@Svenum figured out the issue and made a fix. Releasing v0.13 shortly.
