### ISSUE TITLE
0.13 breaks `traefik.docker.network`

### ISSUE THREAD

**Issue by hcooper** [jittering/traefik-kop#23]
Switching from 0.12.1 to 0.13 breaks `traefik.docker.network` (it goes back to using the host's IP, not the container's).

I've not investigated further yet, but opening an issue in case others run into it.

**Comment by chetan** [comment]
@hcooper are you able to enable debug logging on `traefik-kop` (by exporting the `DEBUG=1` env var) and capture the logs for the service in question?
