### ISSUE TITLE
router tls entry missing: router.tls=true without resolver is ignored

### ISSUE THREAD

**Issue by mwacker-sms** [jittering/traefik-kop#32]
Hi,
i am running traefik version  v2.11 (current latest as of writing) in combination with the current traefik-kop version (v0.13.2).
So far everything works right out of the box in my simple setup (one docker host with traefik, another one with traefik-kop) and the router configuration is updated on traeffic.

Since i am not using a certresolver but certificate files configured in my main traefik instance i have not configured a cert resolver.
I observed a strange behaviour by moving one of my services from the traefik host (where it worked just fine) to the traefik-kop host where it lost the tls configuration.

The labels in use (minimal example):
```
[...]
ports: 
  - 123...
labels:
  traefik.enable: true
  traefik.http.routers.https_backend.rule: "Host(`hostname.example`) && PathPrefix(`/api`)"
  traefik.http.routers.https_backend.entrypoints: websecure
  traefik.http.routers.https_backend.tls: true
  traefik.http.routers.https_backend.service: service_backend
  traefik.http.services.service_backend.loadbalancer.server.port: 123
  traefik.http.services.service_backend.loadbalancer.server.scheme: https
```
In the Traefik-Dashboard the router was successfully created, but without any TLS configuration.

In Redis there was no key `traefik/http/routers/https_backend/tls` set. After i created the key manually with the value  `true` according to the [Traefic KV doc](https://doc.traefik.io/traefik/routing/providers/kv/) the TLS configuration of the router was set as expected.

Since at least i expected the behaviour of traefik-kop to respect the same label tag configuration as traefik itself and the above configuration example is working fine in traefic itself i guess this might be a bug in traefik-kop.

After some time i found a workaround by adding a default certresolver label (`traefik.http.routers.https_backend.tls.certresolver:default`) which at least worked with my configuration. But since this is not necessary on treafik i consider this behaviour as unexpected.

**Comment by chetan** [comment]
Try setting the certresolver val as shown in the readme. I believe traefik will use defaults at certain times.

**Comment by mwacker-sms** [comment]
It does work as a workaround, but there are warnings in the traefik log, since I have no certresolver configured traefik is complaining of a missing default certresolver.
As i wrote above, the behaviour of traefik-kop is different from traefik in this case and somewhat unexpected. 
So traefik-kop should support the label `traefik.http.routers.https_backend.tls: true` and set the correct redis entry as mentioned above.

**Comment by michaelkrieger** [comment]
Also experiencing this.

Working configuration as follows:
**container**
```
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.http-echo.rule=Host(`host.mydomain.com`) && PathPrefix(`/http-echo`)'
      - 'traefik.http.routers.http-echo.tls=true'
      - 'traefik.http.services.http-echo.loadBalancer.server.port=1234'
```
**traefik**
```
    labels:
      # Set up Wildcard Certificates for use in other hosts by just specifying tls=true to the router
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.tls.domains[0].main=${DOMAINNAME:?err}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAINNAME:?err}"
```

This works normally, however with traefik-kop, I need to add:
```
      - "traefik.http.routers.http-echo.tls.certresolver=le"
```
to each container to get it to work (where `le` is my defined provider), rather than rely on the global setting of the configuration.

In theory, traefik-kop should handle this, no?

**Comment by chetan** [comment]
@michaelkrieger wrote:
> Ideally, it should use the existing certificate the way Traefik does. 

You're right, however thinking about this some more, I believe the issue is that `.tls=true` without a `certresolver` tells `traefik` to use the default. In our case, `kop` does not what your default is and so cannot create the appropriate router config for you. Your `traefik` service does have this config internally and so inserts it while processing the labels.

> At the very least, it should not silently ignore the TLS option and should trigger a warning/error. Just spent a bunch of time figuring out why it wasn't working correctly, and it turns out that TLS wasn't on.

This is a good point, I'll see if I can manage this. I leverage `traefik`'s label->config code so it may already be dropped by the time I see it.

**Comment by chetan** [comment]
Added a warning like the following:

```
time="2024-06-30T17:58:20-04:00" level=info msg="publishing http://192.168.100.100:5555" service=hello1@docker service-type=http
time="2024-06-30T17:58:20-04:00" level=warning msg="router hello1@docker has no TLS cert resolver" service=hello1@docker service-type=http
```

**Comment by BenLangers** [comment]
Hi, I am having the exact same issue. Traefik setup with external certificates, loaded through dynamic configuration. traefik_kop on a separate docker swarm cluster. The hosts in the swarm log the warning mentioned above, but this does not resolve anything. The traefik router for that container does not have tls enabled, and I do not have a cert resolver setup to reference in this configuration. 
How can I get traefik_kop to correctly enable tls for that router??

**Comment by chetan** [comment]
@BenLangers can you explain a bit more about your setup? At least the set of docker traefik labels for the container in question?

**Comment by middleagedman** [comment]
Same issue here.. Cannot figure out why Traefik is not routing to this host.  But the routers and services look ok for it except for the TLS icon is missing.    Here's what I have on the remote host with traefik-kop

   labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.domain.org`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana-https.rule=Host(`grafana.domain.org`)"
      - "traefik.http.routers.grafana-https.entrypoints=websecure"
      - "traefik.http.routers.grafana-https.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

**Comment by chetan** [comment]
Did you set up a default certresolver? It should look like

```yaml
certificatesResolvers:
  default:
    acme:
      # acme config...
entryPoints:
  websecure:
    address: :443
    http:
      tls:
        certResolver: "default"
```

If not, you have to specify the resolver to use in your labels.
