### ISSUE TITLE
Running traefik-kop on the same host running traefik

### ISSUE THREAD

**Issue by estebanthi** [jittering/traefik-kop#34]
Hi,

When traefik-kop is running on the same host running traefik, sometimes it works and sometimes it doesn't. The services are successfully discovered, but they are, with the routers, duplicated because they are provided both by the Docker provider and the Redis providers. When I want to access a service and the router used is the one from Docker, it doesn't work because the router routes to the IP of the container (and I don't want the service container to belong to the traefik network so the gateway timeout error is expected). Else, it works. Is there any way to give a higher priority to the Redis routers, or is there any other workaround?

For context, I'm using Ansible to deploy my applications on several nodes. But I don't want the docker compose files to be dependent on the node where the corresponding containers are hosted, which happens without traefik-kop because I have to modify the docker compose files of the node running traefik to connect the containers to the traefik network, which is what I'm doing for now and it works, but it is not what I want. Ideally, I just want to deploy traefik-kop on all the nodes, included the one running traefik, and don't have to modify the docker compose files of the node running traefik. I could use a VM just for traefik, but I think it's a bit overkill and not very convenient.

**Comment by undaunt** [comment]
Sounds like you may be better served leveraging docker contexts and managing all of the deployment from a single node? That's what I'm doing and I switch contexts from my primary Traefik node and Traefik-kop is installed on all secondary nodes.

**Comment by estebanthi** [comment]
I just tried and it's fine this way. Thanks!
